add build timestamp and expiration date based time sanity check
https://phabricator.whonix.org/T151

diff --git a/usr/lib/anon-shared-helper-scripts/te_pe_tb_check b/usr/lib/anon-shared-helper-scripts/te_pe_tb_check
--- a/usr/lib/anon-shared-helper-scripts/te_pe_tb_check
+++ b/usr/lib/anon-shared-helper-scripts/te_pe_tb_check
@@ -4,6 +4,11 @@
 ## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
+## Exit codes of this script get interpreted by sdwdate.
+## exit 0
+## exit 1: wait, retry and warning icon
+## exit 2: wait, retry and error icon
+
 set -o pipefail
 set -e errtrace
 
@@ -29,9 +34,33 @@ te_pe_tb_check() {
       VM="Could not determine if this is gateway or workstation. Please report this bug."
    fi
 
+   clock_causes="\
+<br><br>Possible causes:<br>
+- The host clock is wrong -> shut down the VM, fix the clock in the host and restart the VM.<br>
+- The VM clock is wrong -> manually fix the clock. Restart Tor if necessary. Then restart sdwdate.<br>
+- A host clock attack succeeded.<br>
+- A hardware issue (for example bios clock issues).<br>"
+
    ## Debugging.
    true "$FUNCNAME: CURL: $CURL"
    true "$FUNCNAME: LD_PRELOAD: $LD_PRELOAD"
+
+   if [ -e /usr/share/timesanitycheck/shared ]; then
+      ## provides: time_sanity_check
+      ## sets: time_sanity_check_exit_code
+      ## sets: time_sanity_check_msg_static
+      source /usr/share/timesanitycheck/shared
+      time_sanity_check
+      if [ "$time_sanity_check_exit_code" = "0" ]; then
+         true "$time_sanity_check_msg_static"
+      else
+         echo "$time_sanity_check_msg_static
+$clock_causes"
+         if [ "$VM" = "Gateway" ]; then
+            exit 1
+         fi
+      fi
+   fi
 
    ## Sets: TOR_ENABLED
    check_tor_enabled_do
@@ -128,16 +157,6 @@ Start Menu -> Applications -> System -> whonixsetup - Connection Wizard or in Te
 
    current_unixtime="$(date +"%s")"
 
-   ## "The clock is slower than the build timestamp."
-   ## "The clock is faster than the expiration timestamp"
-
-   clock_causes="\
-<br><br>Possible causes:<br>
-- The host clock is wrong -> shut down the VM, fix the clock in the host and restart the VM.<br>
-- The VM clock is wrong -> manually fix the clock. Restart Tor if necessary. Then restart sdwdate.<br>
-- A host clock attack succeeded.<br>
-- A hardware issue (for example bios clock issues).<br>"
-
    if [ "$tor_consensus_valid_after_exit_code" = "0" ] && [ "$tor_consensus_valid_until_exit_code" = "0" ]; then
       clock_tor_consensus_check_result="ok"
       if [ "$current_unixtime" -ge "$tor_consensus_valid_after_unixtime" ]; then
@@ -164,9 +183,10 @@ Start Menu -> Applications -> System -> whonixsetup - Connection Wizard or in Te
 
    echo "$clock_tor_consensus_check_msg"
 
-   ## TODO: maybe only useful on the gateway
    if [ ! "$clock_tor_consensus_check_result" = "ok" ]; then
-      exit "1"
+      if [ "$VM" = "Gateway" ]; then
+         exit "1"
+      fi
    fi
 
    if [ "$tor_circuit_established" = "1" ]; then
