fixes

diff --git a/usr/lib/anon-shared-helper-scripts/terminal-wrapper b/usr/lib/anon-shared-helper-scripts/terminal-wrapper
--- a/usr/lib/anon-shared-helper-scripts/terminal-wrapper
+++ b/usr/lib/anon-shared-helper-scripts/terminal-wrapper
@@ -9,7 +9,7 @@ set -e
 if command -v konsole >/dev/null 2>&1; then
    [ -n "$terminal_emulator_app" ] || terminal_emulator_app="konsole"
 elif command -v xterm >/dev/null 2>&1; then
-   [ -n "$terminal_emulator_app" ] || terminal_emulator_app="xterm -e"
+   [ -n "$terminal_emulator_app" ] || terminal_emulator_app="xterm"
 elif command -v xfce4-terminal >/dev/null 2>&1; then
    [ -n "$terminal_emulator_app" ] || terminal_emulator_app="xfce4-terminal"
 else
@@ -17,9 +17,17 @@ else
 
 PPID: $PPID
 $0 was called by: $(ps --no-headers -o command $PPID)" || true
-   kdialog --sorry "$error_message" || true
-   zenity --error --text "$error_message" || true
+   kdialog --sorry "$error_message" >/dev/null 2>&1 || true
+   zenity --error --text "$error_message" >/dev/null 2>&1 || true
    echo "$error_message" >&2
+fi
+
+if [ "$terminal_emulator_app" = "xterm" ]; then
+   [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="-e"
+fi
+
+if [ "$terminal_emulator_app" = "xfce4-terminal" ]; then
+   [ -n "$terminal_emulator_extra_args" ] || terminal_emulator_extra_args="--execute"
 fi
 
 if command -v qubesdb-read >/dev/null 2>&1; then
@@ -34,4 +42,4 @@ else
    fi
 fi
 
-$terminal_emulator_app $terminal_emulator_extra_args "$@ ; bash"
+$terminal_emulator_app $terminal_emulator_extra_args $@
