sanity test

diff --git a/unicode-testscript b/unicode-testscript
--- a/unicode-testscript
+++ b/unicode-testscript
@@ -26,7 +26,7 @@ folder_list="Assembly  Bash  C  C#  C++  Go  Java  JavaScript  Python  RegEx  Ru
 total_file_counter=0
 
 process_file() {
-  local file_name
+  local file_name file_content
   file_name="$1"
   test -r "$file_name"
   base_name="$(basename "$file_name")"
@@ -72,6 +72,21 @@ process_file() {
     exit 1
   fi
   ## unicode-show non-zero exit code.
+
+  if ! cat -- "$file_name" | sanitize-string nolimit >/dev/null ; then
+    ## unicode-show exit code 0.
+    printf "%s\n" "$0: ERROR: Failed to sanitize string using 'sanitize-string' (stdin check) in file '$file_name'." >&2
+    exit 1
+  fi
+
+  ## > ./unicode-testscript: line 83: warning: command substitution: ignored null byte in input
+  file_content="$(cat -- "$file_name")"
+
+  if ! sanitize-string nolimit "$file_content" >/dev/null ; then
+    ## unicode-show exit code 0.
+    printf "%s\n" "$0: ERROR: Failed to sanitize string using 'sanitize-string' (command check) in file '$file_name'." >&2
+    exit 1
+  fi
 
   return 0
 }
