improve unicode test script

diff --git a/unicode-testscript b/unicode-testscript
--- a/unicode-testscript
+++ b/unicode-testscript
@@ -49,17 +49,25 @@ process_file() {
   ## So if unicode-show was to exit 0, then it would have failed to find unicode.
   if unicode-show "$file_name" >/dev/null ; then
     ## unicode-show exit code 0.
-    printf "%s\n" "$0: ERROR: Failed to find unicode using unicode-show (file check) in file '$file_name'."  >&2
+    printf "%s\n" "$0: ERROR: Failed to find unicode using 'unicode-show' (file check) in file '$file_name'." >&2
     exit 1
   fi
 
   if cat -- "$file_name" | unicode-show >/dev/null ; then
-    ## unicode-show exit code 0.
-    printf "%s\n" "$0: ERROR: Failed to find unicode using cat unicode-show (stdin check) in file '$file_name'."  >&2
+    ## unicode-show exit code non-zero.
+    printf "%s\n" "$0: ERROR: Failed to find unicode using unicode-show (stdin check) in file '$file_name'." >&2
     exit 1
   fi
+  ## unicode-show exit code 0.
 
-  ## unicode-show non-zero exit code.
+  ## 'stcatv' should sanitize. Therefore 'unicode-show' should not find any unicode and exit 0.
+  ## Check if there is a non-zero exit code in this pipe, because if so, that's a bug.
+  if ! stcatv "$file_name" | unicode-show >/dev/null ; then
+    ## unicode-show exit code 0.
+    printf "%s\n" "$0: ERROR: Failed to sanitize string using 'stcatv' in file '$file_name'." >&2
+    exit 1
+  fi
+  ## unicode-show non-zero exit code..
 
   return 0
 }
