fix; code simplification

diff --git a/unicode-testscript b/unicode-testscript
--- a/unicode-testscript
+++ b/unicode-testscript
@@ -107,4 +107,37 @@ while IFS= read -r -d '' file_name; do
   process_file "$file_name"
 done < <(find "$TMP/suspicious-ascii-test" -maxdepth 1 -type f -not -iwholename '*.git*' -print0 )
 
+if [ ! "$(printf "%s" "test" | stcatn | wc -l)" = "1" ]; then
+  printf "%s\n" "$0: ERROR: 1" >&2
+  exit 1
+fi
+
+if [ ! "$(printf "%s\n" "test" | stcatn | wc -l)" = "1" ]; then
+  printf "%s\n" "$0: ERROR: 2" >&2
+  exit 1
+fi
+
+if [ ! "$(printf "%s\n" "test" | stcatn | wc -l)" = "1" ]; then
+  printf "%s\n" "$0: ERROR: 3" >&2
+  exit 1
+fi
+
+if [ ! "$(printf "%s\n\n" "test" | stcatn | wc -l)" = "2" ]; then
+  printf "%s\n" "$0: ERROR: 4" >&2
+  exit 1
+fi
+
+mkdir --parents "$TMP/suspicious-whitespace-test"
+printf "\n \n " | sponge -- "$TMP/suspicious-whitespace-test/1.txt"
+
+if ! stcatn "$TMP/suspicious-whitespace-test/1.txt" | unicode-show ; then
+  printf "%s\n" "$0: ERROR: 5" >&2
+  exit 1
+fi
+
+if [ ! "$(stcatn "$TMP/suspicious-whitespace-test/1.txt" | wc -l)" = "3" ]; then
+  printf "%s\n" "$0: ERROR: 6" >&2
+  exit 1
+fi
+
 printf "%s\n" "$0: INFO: OK"
