work on anondate

diff --git a/usr/lib/helper-scripts/anondate-tester b/usr/lib/helper-scripts/anondate-tester
--- a/usr/lib/helper-scripts/anondate-tester
+++ b/usr/lib/helper-scripts/anondate-tester
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-export TOR_LOG="/var/log/tor/log"
+## Copyright (C) 2014 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
+## See the file COPYING for copying conditions.
+
+
+if [ "$(id -u)" != "0" ]; then
+   echo "$0: ERROR: Must run as root."
+   exit 112
+fi
 
 cmd_item_list=(
 "--has-consensus"
