anondate

diff --git a/usr/lib/helper-scripts/te_pe_tb_check b/usr/lib/helper-scripts/te_pe_tb_check
--- a/usr/lib/helper-scripts/te_pe_tb_check
+++ b/usr/lib/helper-scripts/te_pe_tb_check
@@ -5,8 +5,8 @@
 
 ## Exit codes of this script get interpreted by sdwdate.
 ## exit 0
-## exit 1: wait, retry and warning icon
-## exit 2: wait, retry and error icon
+## exit 1: wait, retry and error icon
+## exit 2: wait, retry and busy icon
 
 set -o pipefail
 set -e errtrace
@@ -219,7 +219,7 @@ exit_success_if_tor_circuit_already_established() {
 }
 
 run_anondate_set() {
-   echo "Running anondate-set..." >&2
+   echo "$0: Running anondate-set..." >&2
    ## This has a sudoers exception.
    anondate-set
    exit 2
diff --git a/usr/sbin/anondate b/usr/sbin/anondate
--- a/usr/sbin/anondate
+++ b/usr/sbin/anondate
@@ -4,6 +4,7 @@
 ## Copyright (C) 2014 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
+set -e
 set -o pipefail
 
 variables() {
@@ -154,8 +155,10 @@ parse_cmd_options() {
 }
 
 root_check() {
-   if [ "$(id -u)" != "0" ]; then
-      echo "$0: ERROR: Must run as root."
+   if [ "$(whoami)" = "sdwdate" ]; then
+      true
+   elif [ "$(id -u)" != "0" ]; then
+      echo "$0: ERROR: Must run as root." >&2
       exit 112
    fi
 }
