anondate

diff --git a/usr/sbin/anondate-set b/usr/sbin/anondate-set
--- a/usr/sbin/anondate-set
+++ b/usr/sbin/anondate-set
@@ -55,11 +55,20 @@ elif [ "$anondate_get_exit_code" = "2" ]; then
       echo "$0: INFO: Creating status file '$anondate_tor_certificate_lifetime_set_file'."
       touch "$anondate_tor_certificate_lifetime_set_file"
       echo "$0: INFO: Done, created status file '$anondate_tor_certificate_lifetime_set_file'."
+
       ## If clock was too fast, restart of Tor is required.
-      echo "$0: INFO: Tor restart using 'systemctl restart tor@default'..."
-      ## TODO: vs sdwdate systemd hardening
-      systemctl --no-pager restart tor@default
-      echo "$0: INFO: Tor restart done."
+      if [ "$(whoami)" = "sdwdate" ]; then
+         echo "$0: INFO: Tor restart using by creating \
+/run/sdwdate/request_tor_restart request file."
+         touch /run/sdwdate/request_tor_restart
+      elif [ "$(id -u)" = "0" ]; then
+         sudo -u sdwdate touch /run/sdwdate/request_tor_restart
+      else
+         echo "$0: ERROR: Tor restart not implemented for users other than \
+root and sdwdate." >&2
+         exit 112
+      fi
+
       exit_code=2
    fi
 fi
