anondate-get: do not show time earlier than minimum-unixtime-show

diff --git a/usr/sbin/anondate-get b/usr/sbin/anondate-get
--- a/usr/sbin/anondate-get
+++ b/usr/sbin/anondate-get
@@ -72,6 +72,15 @@ exit_handler() {
    exit "$exit_code"
 }
 
+minimum_time_check() {
+   if ! minimum-time-check "$time_result_unixtime" ; then
+      echo "$0: ERROR: time_result '$time_result' unixtime '$time_result_unixtime' earlier than minimum-unixtime-show '$(minimum-unixtime-show)'" >&2
+      exit_code=1
+      exit 1
+   fi
+   echo "$0: INFO: time_result later than minimum-unixtime-show, ok." >&2
+}
+
 exit_code=1
 
 trap exit_handler EXIT
@@ -116,7 +125,8 @@ fi
 # if anondate --has-consensus ; then
 # echo "$0: INFO: has Tor consensus, ok." >&2
 
-if middle_range="$(anondate --show-middle-range)" ; then
+if time_result="$(anondate --show-middle-range)" ; then
+   time_result_unixtime="$(date --utc --date="$time_result" "+%s")"
    valid_after="$(anondate --show-valid-after)"
    ## example valid_after:
    ## 2021-01-21 15:00:00
@@ -124,17 +134,19 @@ if middle_range="$(anondate --show-middle-range)" ; then
    ## example valid_until:
    ## 2021-01-21 18:00:00
 
-   range_info="valid_after: $valid_after | middle_range: $middle_range | valid_until: $valid_until"
+   range_info="valid_after: $valid_after | middle_range: $time_result | valid_until: $valid_until"
 
-   if [ "$middle_range" = "" ]; then
+   if [ "$time_result" = "" ]; then
       echo "$0: WARNING: Tor consensus time middle range result empty." >&2
    elif anondate --current-time-in-valid-range ; then
       echo "$0: INFO: local system time is already within valid range, ok. ($range_info)" >&2
+      minimum_time_check
       exit_code=4
    else
       echo "$0: WARNING: local system time is NOT with valid time range. ($range_info)" >&2
-      echo "$0: INFO: middle_range: '$middle_range'" >&2
-      echo "$middle_range"
+      echo "$0: INFO: middle_range: '$time_result'" >&2
+      minimum_time_check
+      echo "$time_result"
       exit_code="0"
       exit 0
    fi
@@ -159,6 +171,7 @@ else
       else
          echo "$0: INFO: Clock EARLIER than Tor certificate life date." >&2
       fi
+      minimum_time_check
       echo "$time_result"
       exit_code=2
       exit 2
