anondate

diff --git a/usr/sbin/anondate-get b/usr/sbin/anondate-get
--- a/usr/sbin/anondate-get
+++ b/usr/sbin/anondate-get
@@ -83,11 +83,18 @@ if anondate --has-consensus ; then
 fi
 
 if anondate --tor-cert-lifetime-invalid ; then
-   echo "$0: WARNING: Tor certificate lifetime invalid." >&2
+   echo "$0: WARNING: Tor certificate lifetime invalid according to Tor log. This information might be outdated and not matter." >&2
    if time_result="$(anondate --tor-cert-valid-after)" ; then
       echo "$0: INFO: Tor certificate life date: $time_result" >&2
-      echo "$time_result"
-      exit 0
+      time_result_unixtime="$(date --utc --date="$time_result" "+%s")"
+      current_unixtime="$(date --utc "+%s")"
+      if [ "$time_result_unixtime" -ge "$time_result_unixtime" ]; then
+         echo "$0: INFO: Clock already later than Tor certificate life date, ok." >&2
+      else
+         echo "$0: WARNING: Clock earlier later than Tor certificate life date, ok." >&2
+         echo "$time_result"
+         exit 0
+      fi
    else
       echo "$0: WARNING: Could not find out Tor certificate life date." >&2
    fi
