anondate

diff --git a/usr/sbin/anondate b/usr/sbin/anondate
--- a/usr/sbin/anondate
+++ b/usr/sbin/anondate
@@ -4,6 +4,7 @@
 ## Copyright (C) 2014 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
 ## See the file COPYING for copying conditions.
 
+#set -x
 set -e
 set -o pipefail
 
@@ -164,7 +165,12 @@ root_check() {
 }
 
 has_consensus() {
+   if ! test -r "$TOR_DIR". ; then
+      echo "$0: ERROR: Cannot read TOR_DIR: '$TOR_DIR'" >&2
+      exit 4
+   fi
    if [ ! -r "$consensus" ]; then
+      echo "$0: ERROR: Cannot read consensus file: '$consensus'" >&2
       exit 4
    fi
    local grep_exit_code="0"
@@ -177,19 +183,25 @@ has_consensus() {
 }
 
 show-valid-after() {
-   vstart="$(sed -n "/^valid-after \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
+   vstart="$(/usr/lib/helper-scripts/tor_consensus_valid-after.py)"
+   #vstart="$(sed -n "/^valid-after \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
+   if [ "$vstart" = "" ]; then
+      exit 1
+   fi
    if [ "$show_valid_after_" = "true" ]; then
       echo "$vstart"
    fi
-   #/usr/lib/helper-scripts/tor_consensus_valid-after.py
 }
 
 show-valid-until() {
-   vend="$(sed -n "/^valid-until \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
+   vend="$(/usr/lib/helper-scripts/tor_consensus_valid-until.py)"
+   #vend="$(sed -n "/^valid-until \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
+   if [ "$vstart" = "" ]; then
+      exit 1
+   fi
    if [ "$show_valid_until_" = "true" ]; then
       echo "$vend"
    fi
-   #/usr/lib/helper-scripts/tor_consensus_valid-until.py
 }
 
 show-middle-range() {
diff --git a/usr/sbin/anondate-get b/usr/sbin/anondate-get
--- a/usr/sbin/anondate-get
+++ b/usr/sbin/anondate-get
@@ -72,21 +72,28 @@ fi
 
 ## TODO: Tor cert valid after must be after Tor consensus middle range to avoid using stale Tor consensus
 
-if anondate --has-consensus ; then
-   echo "$0: INFO: has Tor consensus, ok." >&2
-   if anondate --current-time-in-valid-range ; then
+## Needs acccess to TOR_DIR /var/lib/tor.
+# if anondate --has-consensus ; then
+# echo "$0: INFO: has Tor consensus, ok." >&2
+
+if middle_range="$(anondate --show-middle-range)" ; then
+   if [ "$middle_range" = "" ]; then
+      echo "$0: WARNING: Tor consensus time middle range result empty." >&2
+   elif anondate --current-time-in-valid-range ; then
       echo "$0: INFO: current time in valid in range, ok." >&2
    else
       echo "$0: WARNING: current time in NOT in valid range." >&2
-      if middle_range="$(anondate --show-middle-range)" ; then
-         echo "$0: INFO: middle_range: '$middle_range'" >&2
-         echo "$middle_range"
-         exit 0
-      fi
+      echo "$0: INFO: middle_range: '$middle_range'" >&2
+      echo "$middle_range"
+      exit 0
    fi
 else
-   echo "$0: WARNING: has no Tor consensus yet." >&2
+   echo "$0: WARNING: could not determine Tor consensus time middle range." >&2
 fi
+
+# else
+#    echo "$0: WARNING: has no Tor consensus yet." >&2
+# fi
 
 if anondate --tor-cert-lifetime-valid ; then
    echo "$0: INFO: Tor certificate lifetime valid, ok." >&2
