redesign recovery from slow clock

diff --git a/usr/sbin/anondate-set b/usr/sbin/anondate-set
--- a/usr/sbin/anondate-set
+++ b/usr/sbin/anondate-set
@@ -31,6 +31,20 @@ exit_code=1
 
 trap exit_handler EXIT
 
+restart_tor_if_running() {
+   if systemctl --no-pager --no-block status tor@default ; then
+      true "$0: INFO: tor@default running, stopping..."
+      systemctl --no-pager --no-block stop tor@default || true
+      true "$0: INFO: Deleting Tor consensus..."
+      ## provided by package helper-scripts
+      anon-consensus-del
+      true "$0: INFO: Restart Tor..."
+      systemctl --no-pager --no-block start tor@default || true
+   else
+      true "$0: INFO: tor@default not running, not deleting Tor consensus and not restarting Tor."
+   fi
+}
+
 set_date() {
    unixtime="$(date --utc --date "$time_result" "+%s")"
    if ! minimum-time-check "$unixtime" ; then
@@ -89,13 +103,10 @@ elif [ "$anondate_get_exit_code" = "2" ]; then
       echo "$0: INFO: Done, created status file '$anondate_tor_certificate_lifetime_set_file'."
 
       ## If clock was too fast, restart of Tor is required.
-      if [ "$(whoami)" = "sdwdate" ]; then
-         echo "$0: INFO: Deleting Tor consensus and Tor restart using by creating /run/sdwdate/request_tor_restart request file."
-         touch /run/sdwdate/request_tor_restart
-      elif [ "$(id -u)" = "0" ]; then
-         sudo -u sdwdate touch /run/sdwdate/request_tor_restart
+      if [ "$(id -u)" = "0" ]; then
+         restart_tor_if_running
       else
-         echo "$0: ERROR: Tor restart not implemented for users other than 'root' and 'sdwdate'." >&2
+         echo "$0: ERROR: Tor restart not implemented for users other than 'root'." >&2
          exit_code=112
          exit 112
       fi
