anondate: improve error handling

diff --git a/usr/sbin/anondate b/usr/sbin/anondate
--- a/usr/sbin/anondate
+++ b/usr/sbin/anondate
@@ -8,6 +8,25 @@
 set -e
 set -o pipefail
 
+check_is_not_empty_and_only_one_line() {
+   local varname value number_of_lines
+   varname="$1"
+   value="${!varname}"
+
+   number_of_lines="$(printf '%s\n' "$value" | grep -c '^')"  # Count non-empty lines
+
+   if [ "$number_of_lines" -eq 0 ]; then
+      echo "$0: ERROR: Variable '$varname' is empty or contains only newlines." >&2
+      return 1
+   elif [ "$number_of_lines" -ne 1 ]; then
+      echo "$0: ERROR: Variable '$varname' contains more than one line. Content:
+'$value'" >&2
+      return 1
+   fi
+
+   return 0
+}
+
 variables() {
    [ -n "$TOR_RC" ] || TOR_RC="/etc/tor/torrc"
 
@@ -192,9 +211,7 @@ has_consensus() {
 show-valid-after() {
    vstart="$(/usr/libexec/helper-scripts/tor_consensus_valid-after.py)"
    #vstart="$(sed -n "/^valid-after \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
-   if [ "$vstart" = "" ]; then
-      exit 1
-   fi
+   check_is_not_empty_and_only_one_line vstart
    if [ "$show_valid_after_" = "true" ]; then
       echo "$vstart"
    fi
@@ -203,9 +220,7 @@ show-valid-after() {
 show-valid-until() {
    vend="$(/usr/libexec/helper-scripts/tor_consensus_valid-until.py)"
    #vend="$(sed -n "/^valid-until \(${DATE_RE}\)"'$/s//\1/p; t q; b; :q q' ${consensus})" || exit 1
-   if [ "$vend" = "" ]; then
-      exit 1
-   fi
+   check_is_not_empty_and_only_one_line vend
    if [ "$show_valid_until_" = "true" ]; then
       echo "$vend"
    fi
@@ -215,6 +230,7 @@ show-middle-range() {
    show-valid-after
    show-valid-until
    vmid="$(date --utc --date="${vstart} -0130" +'%F %T')" || exit 1
+   check_is_not_empty_and_only_one_line vmid
    if [ "$show_middle_range_" = "true" ]; then
       echo "$vmid"
    fi
@@ -227,6 +243,7 @@ current_time_is_in_valid_range() {
    ## Debugging.
    #vend="2099-09-03 09:41:29"
    vendchk="$(date --utc --date="${vstart} -0300" +'%F %T')"
+   check_is_not_empty_and_only_one_line vendchk
    if [ ! "${vend}" = "${vendchk}" ]; then
       echo "$0: ERROR: Unexpected valid-until: [vend: '${vend}'] is not [vstart: '${vstart}' + 3h]" >&2
       exit 1
@@ -238,6 +255,7 @@ current_time_is_in_valid_range() {
    #curdate="2099-09-03 09:41:29"
 
    vendcons="$(date --utc --date="${vstart} -0230" +'%F %T')"
+   check_is_not_empty_and_only_one_line vendcons
    order="${vstart}
 ${curdate}
 ${vendcons}"
diff --git a/usr/sbin/anondate-set b/usr/sbin/anondate-set
--- a/usr/sbin/anondate-set
+++ b/usr/sbin/anondate-set
@@ -13,6 +13,25 @@
 set -e
 set -o pipefail
 
+check_is_not_empty_and_only_one_line() {
+   local varname value number_of_lines
+   varname="$1"
+   value="${!varname}"
+
+   number_of_lines="$(printf '%s\n' "$value" | grep -c '^')"  # Count non-empty lines
+
+   if [ "$number_of_lines" -eq 0 ]; then
+      echo "$0: ERROR: Variable '$varname' is empty or contains only newlines." >&2
+      return 1
+   elif [ "$number_of_lines" -ne 1 ]; then
+      echo "$0: ERROR: Variable '$varname' contains more than one line. Content:
+'$value'" >&2
+      return 1
+   fi
+
+   return 0
+}
+
 output_init() {
    rm -f "${anondate_state_folder}/anondate-set-current-message.txt"
    touch "${anondate_state_folder}/anondate-set-current-message.txt"
@@ -95,9 +114,12 @@ restart_tor_if_running() {
 
 set_date() {
    current_time_human_readable="$(date --utc "+%Y-%m-%d %H:%M:%S")"
+   check_is_not_empty_and_only_one_line current_time_human_readable
    current_unixtime="$(date --utc "+%s")"
+   check_is_not_empty_and_only_one_line current_unixtime
 
    time_result_unixtime="$(date --utc --date "$time_result_human_readable" "+%s")"
+   check_is_not_empty_and_only_one_line time_result_unixtime
 
    if [ "$current_unixtime" -ge "$time_result_unixtime" ]; then
       output_cmd "INFO: The 'anondate-get' time_result is earlier than the current system time, ok. Not setting clock backwards."
@@ -198,6 +220,7 @@ anondate_stdout="$(cat "${anondate_state_folder}/anondate-get-stdout.txt")"
 anondate_stderr="$(cat "${anondate_state_folder}/anondate-get-stderr.txt")"
 
 time_result_human_readable="$anondate_stdout"
+check_is_not_empty_and_only_one_line time_result_human_readable
 
 indent_style=false
 output_cmd "$anondate_stderr"
