output

diff --git a/usr/sbin/anondate b/usr/sbin/anondate
--- a/usr/sbin/anondate
+++ b/usr/sbin/anondate
@@ -158,7 +158,7 @@ parse_cmd_options() {
       exit "$?"
    fi
 
-   echo "No option chosen." 2>&1
+   echo "$0: No option chosen." 2>&1
    exit 1
 }
 
@@ -228,7 +228,7 @@ current_time_is_in_valid_range() {
    #vend="2099-09-03 09:41:29"
    vendchk="$(date --utc --date="${vstart} -0300" +'%F %T')"
    if [ ! "${vend}" = "${vendchk}" ]; then
-      echo "ERROR: Unexpected valid-until: [vend: '${vend}'] is not [vstart: '${vstart}' + 3h]" >&2
+      echo "$0: ERROR: Unexpected valid-until: [vend: '${vend}'] is not [vstart: '${vstart}' + 3h]" >&2
       exit 1
    fi
    ## }} Sanity Test
