improved error handling

diff --git a/usr/sbin/autologinchange b/usr/sbin/autologinchange
--- a/usr/sbin/autologinchange
+++ b/usr/sbin/autologinchange
@@ -339,7 +339,12 @@ if [ -x /usr/libexec/user-sysmaint-split/sysmaint-boot ]; then
    fi
 fi
 
-readarray -t user_list < <(/usr/libexec/helper-scripts/get-user-list)
+if ! output=$(/usr/libexec/helper-scripts/get-user-list); then
+    echo "ERROR: Failed to get user list!" >&2
+    exit 1
+fi
+
+readarray -t user_list <<< "$output"
 
 case "${1:-}" in
    '-c')
