Fix several autologinchange issues (collapsing lines in greetd incorrectly, failing to remove effectively empty greetd config files, use of echo rather than printf)

diff --git a/usr/sbin/autologinchange b/usr/sbin/autologinchange
--- a/usr/sbin/autologinchange
+++ b/usr/sbin/autologinchange
@@ -43,10 +43,10 @@ remove_from_config_section() {
 
    mapfile -t lines < "$file_name"
 
-   output=""
+   output=()
    for line in "${lines[@]}"; do
       if [ "${filter_stage}" = '1' ]; then
-         output+="${line}"
+         output+=( "${line}" )
          if [ "${line}" = "[${section}]" ]; then
             filter_stage='2'
          fi
@@ -56,19 +56,19 @@ remove_from_config_section() {
             line_was_removed="true"
             continue
          fi
-         output+="${line}"
+         output+=( "${line}" )
          if [[ "${line}" =~ ^\[.*\]$ ]]; then
             filter_stage='3'
          fi
       else
-         output+="${line}"
+         output+=( "${line}" )
       fi
    done
 
-   printf '%s\n' "${output}" | sponge -- "$file_name"
+   printf '%s\n' "${output[@]}" | sponge -- "$file_name"
 
    if [ "$line_was_removed" = "true" ]; then
-      echo "INFO: Removed line '$remove_line' from section '$section' of file '$file_name'." >&2
+      printf '%s\n' "INFO: Removed line '$remove_line' from section '$section' of file '$file_name'." >&2
    fi
 }
 
@@ -77,35 +77,35 @@ enable_autologin() {
    user="$1"
 
    mkdir --parents -- /etc/lightdm/lightdm.conf.d
-   echo "[Seat:*]
+   printf '%s\n' "[Seat:*]
 autologin-user=${user}" | sponge -- '/etc/lightdm/lightdm.conf.d/40_autologin.conf'
-   echo "INFO: Wrote file '/etc/lightdm/lightdm.conf.d/40_autologin.conf' to enable autologin for account '$user'." >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "INFO: Wrote file '/etc/lightdm/lightdm.conf.d/40_autologin.conf' to enable autologin for account '$user'." >&2
+   printf '%s\n' "$delimiter" >&2
    cat -- '/etc/lightdm/lightdm.conf.d/40_autologin.conf' >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "$delimiter" >&2
 
    mkdir --parents -- /etc/sddm.conf.d
-   echo "[Autologin]
+   printf '%s\n' "[Autologin]
 User=${user}" | sponge -- '/etc/sddm.conf.d/z-autologin.conf'
-   echo "INFO: Wrote file '/etc/sddm.conf.d/z-autologin.conf' to enable autologin for account '$user'." >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "INFO: Wrote file '/etc/sddm.conf.d/z-autologin.conf' to enable autologin for account '$user'." >&2
+   printf '%s\n' "$delimiter" >&2
    cat -- '/etc/sddm.conf.d/z-autologin.conf' >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "$delimiter" >&2
 
    mkdir --parents -- /etc/greetd/config.toml.d
-   echo "[initial_session]
+   printf '%s\n' "[initial_session]
 command = \"/usr/libexec/desktop-config-dist/start-lxqt-session\"
 user = \"${user}\"" | sponge -- '/etc/greetd/config.toml.d/40_autologin.conf'
-   echo "INFO: Wrote file '/etc/greetd/config.toml.d/40_autologin.conf' to enable autologin for account '$user'." >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "INFO: Wrote file '/etc/greetd/config.toml.d/40_autologin.conf' to enable autologin for account '$user'." >&2
+   printf '%s\n' "$delimiter" >&2
    cat -- '/etc/greetd/config.toml.d/40_autologin.conf'
-   echo "$delimiter" >&2
-   echo "INFO: Rebuilding greetd config."
+   printf '%s\n' "$delimiter" >&2
+   printf '%s\n' "INFO: Rebuilding greetd config."
    build-config-file /etc/greetd/config.toml.d /etc/greetd/config.toml
 }
 
 disable_autologin() {
-   local user lightdm_config_file_list file_name file_contents
+   local user lightdm_config_file_list file_name file_contents pattern match_count
    user="$1"
 
    ## TODO: All of these routines may misbehave if the spacing around the =
@@ -125,7 +125,7 @@ disable_autologin() {
       sed -i -E "/$pattern/d" -- "${file_name}"
 
       if [ "$match_count" -gt 0 ]; then
-         echo "INFO: Removed $match_count matching line(s) from file '${file_name}'." >&2
+         printf '%s\n' "INFO: Removed $match_count matching line(s) from file '${file_name}'." >&2
       else
          true "INFO: No matching lines found in file '${file_name}'."
       fi
@@ -135,7 +135,7 @@ disable_autologin() {
       file_contents="$(cat -- "${file_name}")"
       if [ -z "${file_contents}" ] \
          || [ "${file_contents}" = '[Seat:*]' ]; then
-         echo "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
+         printf '%s\n' "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
          safe-rm --verbose -- "${file_name}"
       fi
    done
@@ -149,7 +149,7 @@ disable_autologin() {
       file_contents="$(cat -- "${file_name}")"
       if [ -z "${file_contents}" ] \
          || [ "${file_contents}" = '[Autologin]' ]; then
-         echo "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
+         printf '%s\n' "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
          safe-rm --verbose -- "${file_name}"
       fi
    done
@@ -161,24 +161,24 @@ disable_autologin() {
       remove_from_config_section "${file_name}" 'initial_session' "command = \"/usr/libexec/desktop-config-dist/start-lxqt-session\""
       remove_from_config_section "${file_name}" 'initial_session' "user = \"${user}\""
       true "INFO: Processed autologin configuration removal check for account '$user' from file '$file_name'."
-      file_content="$(cat -- "${file_name}")"
+      file_contents="$(cat -- "${file_name}")"
       if [ -z "${file_contents}" ] \
          || [ "${file_contents}" = '[initial_session]' ]; then
-         echo "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
+         printf '%s\n' "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
          safe-rm --verbose -- "${file_name}"
       fi
    done
-   echo "INFO: Rebuilding greetd config."
+   printf '%s\n' "INFO: Rebuilding greetd config."
    build-config-file /etc/greetd/config.toml.d /etc/greetd/config.toml
 }
 
 enable_sysmaint_autologin() {
    mkdir --parents -- /etc/user-sysmaint-split.conf.d
-   echo 'sysmaint-autologin=yes' | sponge -a -- /etc/user-sysmaint-split.conf.d/40_autologin.conf
-   echo "INFO: Wrote autologin configuration for account 'sysmaint' to file '/etc/user-sysmaint-split.conf.d/40_autologin.conf'." >&2
-   echo "$delimiter" >&2
+   printf '%s\n' 'sysmaint-autologin=yes' | sponge -a -- /etc/user-sysmaint-split.conf.d/40_autologin.conf
+   printf '%s\n' "INFO: Wrote autologin configuration for account 'sysmaint' to file '/etc/user-sysmaint-split.conf.d/40_autologin.conf'." >&2
+   printf '%s\n' "$delimiter" >&2
    cat -- /etc/user-sysmaint-split.conf.d/40_autologin.conf >&2
-   echo "$delimiter" >&2
+   printf '%s\n' "$delimiter" >&2
 }
 
 disable_sysmaint_autologin() {
@@ -189,10 +189,10 @@ disable_sysmaint_autologin() {
       fi
       sed -i '/^sysmaint-autologin=/d' -- "${file_name}"
       ## TODO: Report only actually removed instances similar to disable_autologin function.
-      echo "INFO: Removed autologin configuration for account 'sysmaint' from file '${file_name}'." >&2
+      printf '%s\n' "INFO: Removed autologin configuration for account 'sysmaint' from file '${file_name}'." >&2
       file_contents="$(cat -- "${file_name}")"
       if [ -z "${file_contents}" ]; then
-         echo "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
+         printf '%s\n' "INFO: File '$file_name' contains no meaningful configuration data, removing." >&2
          safe-rm --verbose -- "${file_name}"
       fi
    done
@@ -203,12 +203,12 @@ validate_username() {
 
    user="${1:-}"
    if [ -z "${user}" ]; then
-      echo "ERROR: No username provided. Please specify a username." >&2
+      printf '%s\n' "ERROR: No username provided. Please specify a username." >&2
       exit 1
    fi
 
    if ! id "${user}" &>/dev/null ; then
-      echo "ERROR: Account '$user' does not exist. Please check the username and try again." >&2
+      printf '%s\n' "ERROR: Account '$user' does not exist. Please check the username and try again." >&2
       exit 1
    fi
 
@@ -220,7 +220,7 @@ validate_username() {
       fi
    done
    if [ "${found_user}" = 'n' ]; then
-      echo "ERROR: Account '$user' is not a normal user account. Please check the username and try again." >&2
+      printf '%s\n' "ERROR: Account '$user' is not a normal user account. Please check the username and try again." >&2
       exit 1
    fi
 }
@@ -262,7 +262,7 @@ cli_enable_autologin() {
    if [ "${user}" = 'sysmaint' ] && [ "${special_sysmaint_handling}" = 'yes' ]; then
       ## Account 'sysmaint' requires special handling.
       if [ "${sysmaint_autologin}" = 'yes' ]; then
-         echo "INFO: Autologin already enabled for account 'sysmaint', exiting." >&2
+         printf '%s\n' "INFO: Autologin already enabled for account 'sysmaint', exiting." >&2
          exit 0
       fi
       enable_sysmaint_autologin
@@ -271,7 +271,7 @@ cli_enable_autologin() {
 
    # shellcheck disable=SC2076
    if [[ " ${autologin_users[*]} " =~ " ${user} " ]]; then
-      echo "INFO: Autologin already enabled for account '$user', exiting." >&2
+      printf '%s\n' "INFO: Autologin already enabled for account '$user', exiting." >&2
       exit 0
    fi
 
@@ -290,7 +290,7 @@ cli_disable_autologin() {
    if [ "${user}" = 'sysmaint' ] && [ "${special_sysmaint_handling}" = 'yes' ]; then
       ## Account 'sysmaint' requires special handling.
       if [ "${sysmaint_autologin}" = 'no' ]; then
-         echo "INFO: Autologin already disabled for account 'sysmaint', exiting." >&2
+         printf '%s\n' "INFO: Autologin already disabled for account 'sysmaint', exiting." >&2
          exit 0
        fi
        disable_sysmaint_autologin
@@ -299,7 +299,7 @@ cli_disable_autologin() {
 
    # shellcheck disable=SC2076
    if ! [[ " ${autologin_users[*]} " =~ " ${user} " ]]; then
-      echo "INFO: Autologin already disabled for account '$user', exiting." >&2
+      printf '%s\n' "INFO: Autologin already disabled for account '$user', exiting." >&2
       exit 0
    fi
 
@@ -308,10 +308,10 @@ cli_disable_autologin() {
 
 warn_on_empty_user_password() {
    if [ -z "$(get_clean_pass "$1")" ]; then
-      echo "${red}WARNING:${nocolor} Account '$1' has no password set." >&2
-      echo "Users can log into this account knowing only the username." >&2
-      echo "You can use the 'pwchange' utility to change this." >&2
-      echo "See https://www.kicksecure.com/wiki/Login for more information." >&2
+      printf '%s\n' "${red}WARNING:${nocolor} Account '$1' has no password set." >&2
+      printf '%s\n' "Users can log into this account knowing only the username." >&2
+      printf '%s\n' "You can use the 'pwchange' utility to change this." >&2
+      printf '%s\n' "See https://www.kicksecure.com/wiki/Login for more information." >&2
    fi
 }
 
@@ -321,10 +321,10 @@ autologinchange() {
    check_root
    create_dm_config_dirs
 
-   echo "[${green}INFO${nocolor}]: This tool enables or disables GUI autologin only." >&2
-   echo "Users present on the system:" >&2
+   printf '%s\n' "[${green}INFO${nocolor}]: This tool enables or disables GUI autologin only." >&2
+   printf '%s\n' "Users present on the system:" >&2
    for user_entry in "${user_list[@]}"; do
-      echo "   ${user_entry}" >&2
+      printf '%s\n' "   ${user_entry}" >&2
    done
 
    read -r -p "Enter the username you would like to toggle autologin for: " -- user
@@ -333,48 +333,48 @@ autologinchange() {
 
    # shellcheck disable=SC2076
    if [[ " ${autologin_users[*]} " =~ " ${user} " ]]; then
-      echo "Account '$user' is currently configured to automatically log in." >&2
+      printf '%s\n' "Account '$user' is currently configured to automatically log in." >&2
       read -r -p "Would you like to disable autologin? [Y/N] " -- disable_yn
 
       if [ "${disable_yn,,}" = 'y' ]; then
          disable_autologin "${user}"
-         echo "SUCCESS: Autologin for account '$user' disabled." >&2
+         printf '%s\n' "SUCCESS: Autologin for account '$user' disabled." >&2
          warn_on_empty_user_password "$user"
       else
-         echo "CANCELLED disabling autologin for account '$user'." >&2
+         printf '%s\n' "CANCELLED disabling autologin for account '$user'." >&2
       fi
       exit 0
    elif [ "${user}" = 'sysmaint' ] && [ "${special_sysmaint_handling}" = 'yes' ]; then
       if [ "${sysmaint_autologin}" = 'yes' ]; then
-         echo "Account 'sysmaint' is currently configured to automatically log in." >&2
+         printf '%s\n' "Account 'sysmaint' is currently configured to automatically log in." >&2
          read -r -p "Would you like to disable autologin for sysmaint mode? [Y/N] " -- disable_yn
 
          if [ "${disable_yn,,}" = 'y' ]; then
             disable_sysmaint_autologin
-            echo "SUCCESS: Autologin for account 'sysmaint' disabled." >&2
+            printf '%s\n' "SUCCESS: Autologin for account 'sysmaint' disabled." >&2
             warn_on_empty_user_password 'sysmaint'
          else
-            echo "CANCELLED disabling autologin for account 'sysmaint'." >&2
+            printf '%s\n' "CANCELLED disabling autologin for account 'sysmaint'." >&2
          fi
          exit 0
       else
-         echo "Account 'sysmaint' is currently NOT configured to automatically log in." >&2
+         printf '%s\n' "Account 'sysmaint' is currently NOT configured to automatically log in." >&2
          read -r -p "Would you like to enable autologin for sysmaint mode? [Y/N] " -- enable_yn
 
          if [ "${enable_yn,,}" = 'y' ]; then
             ## Disable sysmaint autologin first, then re-enable it, to make
-            ## sure other configuration laying around doesn't override the
+            ## sure other configuration lying around doesn't override the
             ## user's choice.
             disable_sysmaint_autologin
             enable_sysmaint_autologin
-            echo "SUCCESS: Autologin for account 'sysmaint' enabled." >&2
+            printf '%s\n' "SUCCESS: Autologin for account 'sysmaint' enabled." >&2
          else
-            echo "CANCELLED enabling autologin for account 'sysmaint'." >&2
+            printf '%s\n' "CANCELLED enabling autologin for account 'sysmaint'." >&2
          fi
          exit 0
       fi
    else
-      echo "Account '$user' is currently NOT configured to automatically log in." >&2
+      printf '%s\n' "Account '$user' is currently NOT configured to automatically log in." >&2
       read -r -p "Are you sure you want to enable autologin for account '$user'? [Y/N] " -- enable_yn
 
       if [ "${enable_yn,,}" = 'y' ]; then
@@ -384,9 +384,9 @@ autologinchange() {
             done
          fi
          enable_autologin "${user}"
-         echo "SUCCESS: Autologin for account '$user' enabled." >&2
+         printf '%s\n' "SUCCESS: Autologin for account '$user' enabled." >&2
       else
-         echo "CANCELLED enabling autologin for account '$user'." >&2
+         printf '%s\n' "CANCELLED enabling autologin for account '$user'." >&2
       fi
       exit 0
    fi
@@ -394,7 +394,7 @@ autologinchange() {
 
 check_root() {
    if [ "$(id -u)" != "0" ]; then
-      echo "ERROR: This must be run as root (sudo)!" >&2
+      printf '%s\n' "ERROR: This must be run as root (sudo)!" >&2
       exit 1
    fi
 }
@@ -405,7 +405,7 @@ create_dm_config_dirs() {
 }
 
 if [ -f '/usr/share/qubes/marker-vm' ]; then
-   echo "INFO: GUI autologin is not applicable to Qubes OS." >&2
+   printf '%s\n' "INFO: GUI autologin is not applicable to Qubes OS." >&2
    exit 0
 fi
 
@@ -462,7 +462,7 @@ fi
 ## TODO: consider cases with leading spaces
 ## TODO: ignore comments
 if grep --quiet --recursive --ignore-case -- '^\[Seat:[^*]' /etc/lightdm; then
-   echo "ERROR: Multi-seat lightdm configuration detected, cannot proceed!" >&2
+   printf '%s\n' "ERROR: Multi-seat lightdm configuration detected, cannot proceed!" >&2
    exit 1
 fi
 
@@ -495,11 +495,11 @@ readarray -t autologin_users < <(
      | sort -u
 )
 
-if ! output="$(/usr/libexec/helper-scripts/get-user-list)"; then
-    echo "ERROR: Failed to get user list!" >&2
+if ! ul_output="$(/usr/libexec/helper-scripts/get-user-list)"; then
+    printf '%s\n' "ERROR: Failed to get user list!" >&2
     exit 1
 fi
 
-readarray -t user_list <<< "$output"
+readarray -t user_list <<< "$ul_output"
 
 "${autologinchange_mode}" "$@"
