improvements

diff --git a/usr/sbin/grub-password-status-check b/usr/sbin/grub-password-status-check
--- a/usr/sbin/grub-password-status-check
+++ b/usr/sbin/grub-password-status-check
@@ -20,6 +20,8 @@ set -o nounset
 set -o errtrace
 set -o pipefail
 
+source /usr/libexec/helper-scripts/package_installed_check.bsh
+
 GRUB_CFG="/boot/grub/grub.cfg"
 
 if [ "$(id -u)" -ne 0 ]; then
@@ -27,19 +29,24 @@ if [ "$(id -u)" -ne 0 ]; then
   exit 2
 fi
 
+if ! pkg_installed 'grub2-common'; then
+  printf "%s\n" "$0: ERROR: Package 'grub2-common' missing." >&2
+  exit 3
+fi
+
 if ! test -d "/boot"; then
   printf "%s\n" "$0: ERROR: Folder '/boot' does not exist." >&2
-  exit 3
+  exit 4
 fi
 
 if ! test -d "/boot/grub"; then
   printf "%s\n" "$0: ERROR: Folder '/boot/grub' does not exist." >&2
-  exit 4
+  exit 5
 fi
 
 if ! test -r "$GRUB_CFG"; then
   printf "%s\n" "$0: ERROR: File '$GRUB_CFG' does not exist or is not readable." >&2
-  exit 5
+  exit 6
 fi
 
 superuser=""
@@ -51,7 +58,7 @@ superuser=$(grep --extended-regexp --only-matching '^set superusers=([\"'\''"]?)
 
 if [ -z "${superuser:-}" ]; then
   printf "%s\n" "$0: ERROR: No valid 'set superusers' entry found in file '$GRUB_CFG'." >&2
-  exit 6
+  exit 7
 fi
 
 password_user=$(grep --extended-regexp --only-matching '^password.*[[:space:]]+([^[:space:]]+)[[:space:]]+grub\.pbkdf2\.sha512\.' "$GRUB_CFG" \
@@ -61,12 +68,12 @@ password_user=$(grep --extended-regexp --only-matching '^password.*[[:space:]]+(
 
 if [ -z "${password_user:-}" ]; then
   printf "%s\n" "$0: ERROR: No valid 'password_pbkdf2' entry found in file '$GRUB_CFG'." >&2
-  exit 7
+  exit 8
 fi
 
 if [ "${superuser:-}" != "${password_user:-}" ]; then
   printf "%s\n" "$0: ERROR: Mismatch: superuser is '$superuser', but password entry is for '$password_user'" >&2
-  exit 8
+  exit 9
 fi
 
 printf "%s\n" "$0: INFO: OK."
