improve error handling

diff --git a/usr/sbin/pwchange_ b/usr/sbin/pwchange_
--- a/usr/sbin/pwchange_
+++ b/usr/sbin/pwchange_
@@ -47,7 +47,13 @@ if [ "$(id -u)" != "0" ]; then
    exit 1
 fi
 
-readarray -t user_list < <(/usr/libexec/helper-scripts/get-user-list)
+if ! output=$(/usr/libexec/helper-scripts/get-user-list); then
+    echo "ERROR: Failed to get user list!" >&2
+    exit 1
+fi
+
+readarray -t user_list <<< "$output"
+
 echo "Users present on the system:"
 for user_entry in "${user_list[@]}"; do
    echo "   ${user_entry}";
