Warn users when hardening account password or login may not be sufficient

diff --git a/usr/sbin/pwchange b/usr/sbin/pwchange
--- a/usr/sbin/pwchange
+++ b/usr/sbin/pwchange
@@ -9,6 +9,9 @@ set -o nounset
 set -o errtrace
 set -o pipefail
 
+# shellcheck source=../libexec/helper-scripts/get_colors.sh
+source /usr/libexec/helper-scripts/get_colors.sh
+
 get_password() {
    ## author of contents of get_password function
    ## Dipto
@@ -54,9 +57,9 @@ fi
 
 readarray -t user_list <<< "$output"
 
-echo "Users present on the system:"
+echo "Users present on the system:" >&2
 for user_entry in "${user_list[@]}"; do
-   echo "   ${user_entry}";
+   echo "   ${user_entry}" >&2
 done
 
 read -r -p "Enter the username whose password you want to change: " user
@@ -67,21 +70,21 @@ if [ "$user" = "" ]; then
 fi
 
 if ! id "$user" &>/dev/null ; then
-   echo "ERROR: User '$user' does not exist. Please check the username and try again." >&2
+   echo "ERROR: Account '$user' does not exist. Please check the username and try again." >&2
    exit 1
 fi
 
-echo -n "Enter the new password for user '$user': "
-echo
+echo -n "Enter the new password for account '$user': " >&2
+echo >&2
 get_password
 first_input="$password"
-echo
+echo >&2
 
-echo -n "Re-enter the new password to confirm: "
-echo
+echo -n "Re-enter the new password to confirm: " >&2
+echo >&2
 get_password
 second_input="$password"
-echo
+echo >&2
 
 if [ ! "$first_input" = "$second_input" ]; then
    echo "ERROR: Passwords do not match. Password has not been changed." >&2
@@ -90,13 +93,13 @@ fi
 
 ## Delete password if the provided new password is blank.
 if [ "$first_input" = "" ]; then
-   read -r -p "WARNING: You are about to delete the password for user '$user'. Continue? [Y/N] " delete_pw_yn
+   read -r -p "WARNING: You are about to delete the password for account '$user'. Continue? [Y/N] " delete_pw_yn
 
    if [ "${delete_pw_yn,,}" = 'y' ]; then
       passwd -d "$user"
-      echo "SUCCESS: Password for user '$user' has been deleted successfully."
+      echo "SUCCESS: Password for account '$user' has been deleted successfully." >&2
    else
-      echo "CANCELLED deleting password for user '$user'."
+      echo "CANCELLED deleting password for account '$user'." >&2
    fi
    exit 0
 fi
@@ -108,4 +111,11 @@ unset first_input
 unset second_input
 unset password
 
-echo "SUCCESS: Password for user '$user' has been updated successfully."
+echo "SUCCESS: Password for account '$user' has been updated successfully." >&2
+
+if /usr/sbin/autologinchange -c "$user"; then
+   echo "${yellow}WARNING:${nocolor} Account '$user' has autologin enabled." >&2
+   echo "Passwordless access to this account is likely still possible." >&2
+   echo "You can use the 'autologinchange' utility to change this." >&2
+   echo "See https://www.kicksecure.com/wiki/Login for more information." >&2
+fi
