Add helper script for rebuilding all DKMS modules, integrate into shim-manage-mok

diff --git a/usr/sbin/shim-manage-mok b/usr/sbin/shim-manage-mok
--- a/usr/sbin/shim-manage-mok
+++ b/usr/sbin/shim-manage-mok
@@ -187,6 +187,13 @@ reboot, to finish the enrollment process."
     return 1
   fi
 
+  log notice "Rebuilding DKMS modules..."
+  if ! rebuild-dkms-modules; then
+    log warning "Some DKMS modules failed to build!"
+    ## Do not return 1 here, the user probably wants to finish enrolling the
+    ## MOK, and fix DKMS later.
+  fi
+
   log notice "\
 $0: INFO: MOK enrollment started.
 To finish the process:
