append-once: check if file is readable / writeable

diff --git a/usr/bin/append-once b/usr/bin/append-once
--- a/usr/bin/append-once
+++ b/usr/bin/append-once
@@ -27,9 +27,20 @@ append_once() {
 
   if ! test -f "$file" ; then
     true "INFO: File does not exist yet: $file"
-  elif grep --fixed-strings --quiet --line-regexp -- "$line" "$file" ; then
-    true "INFO: Line already exists in: $file"
-    return 0
+  else
+    if ! test -r "$file" ; then
+      echo "$0: ERROR: File '$file' not readable!" >&2
+      exit 1
+    fi
+    if grep --fixed-strings --quiet --line-regexp -- "$line" "$file" ; then
+      true "INFO: Line already exists in: $file"
+      return 0
+    fi
+  fi
+
+  if ! test -w "$file" ; then
+    echo "$0: ERROR: File '$file' not writeable!" >&2
+    exit 1
   fi
 
   true "INFO: Appending line to: $file"
