dummy-dependency: fix, implement actual package remove or purge

diff --git a/usr/bin/dummy-dependency b/usr/bin/dummy-dependency
--- a/usr/bin/dummy-dependency
+++ b/usr/bin/dummy-dependency
@@ -70,8 +70,8 @@ Description: dummy-package for '${package_to_replace}'
       echo "$0: INFO: Dummy package created."
    }
 
-   # Validate package name, see
-   # https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
+   ## Validate package name, see
+   ## https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
    if ! grep --quiet '^[a-z0-9]\+[a-z0-9+-.]\+$' -- <<< "${package_to_replace}" ; then
       echo "$0: ERROR: Package name is invalid, check for typos" >&2
       exit 1
@@ -83,7 +83,7 @@ Description: dummy-package for '${package_to_replace}'
    #    exit 1
    # fi
 
-   ## Ensure $TMPDIR is set
+   ## Ensure ${TMPDIR} is set
    if [ ! -v TMPDIR ]; then
       TMPDIR=''
    fi
@@ -126,15 +126,30 @@ Description: dummy-package for '${package_to_replace}'
    #lintian --pedantic --info --display-info "${deb_file_copy}"
 
    echo "$0: Executing: apt-get $yes_option install -- ${deb_file_copy}"
-   if ! apt-get $yes_option install -- "${deb_file_copy}" ; then
+   if apt-get $yes_option install -- "${deb_file_copy}" ; then
+      echo "$0: INFO: Dummy package installed."
+   else
       echo "$0: ERROR: 'apt-get install' command failed!" >&2
       exit 1
    fi
-   echo "$0: INFO: Dummy package installed."
 
-   if [ "${remove_option}" = '--purge' ]; then
+   echo "$0: INFO: Removing package: '${package_to_replace}'"
+   if [ "${remove_option}" = '--remove' ]; then
+      echo "$0: INFO: Not purging old package configuration files... (Because not using '--purge'.)"
+      echo "$0: INFO: Executing: apt-get $yes_option remove -- ${package_to_replace}"
+      if apt-get $yes_option remove -- ${package_to_replace} ; then
+         echo "$0: INFO: Package removed."
+      else
+         echo "$0: ERROR: 'apt-get remove' command failed!" >&2
+      fi
+   elif [ "${remove_option}" = '--purge' ]; then
       echo "$0: INFO: Purging old package configuration files..."
       echo "$0: INFO: Executing: apt-get $yes_option purge -- ${package_to_replace}"
+      if apt-get $yes_option purge -- ${package_to_replace} ; then
+         echo "$0: INFO: Package purged."
+      else
+         echo "$0: ERROR: 'apt-get purge' command failed!" >&2
+      fi
    fi
 
    cleanup
