dummy-dependency: use single apt-get command to remove original package and install dummy package

diff --git a/usr/bin/dummy-dependency b/usr/bin/dummy-dependency
--- a/usr/bin/dummy-dependency
+++ b/usr/bin/dummy-dependency
@@ -20,6 +20,7 @@ show_usage() {
 }
 
 cleanup() {
+   trap '' EXIT
    if [ -n "${TMPDIR_NEW:-}" ] && [ -d "${TMPDIR_NEW}" ]; then
       safe-rm -r -f -- "${TMPDIR_NEW}"
    fi
@@ -125,41 +126,23 @@ Description: dummy-package for '${package_to_replace}'
    ## Sanity test.
    test -r "${deb_file_copy}"
 
-   printf '%s\n' "$0: INFO: Installing dummy package..."
-
    #lintian --pedantic --info --display-info "${deb_file_copy}"
 
-   printf '%s\n' "$0: Executing: apt-get ${yes_option} install -- ${deb_file_copy}"
-   if apt-get ${yes_option} install -- "${deb_file_copy}" ; then
+   if [ "${remove_option}" = '--purge' ]; then
+      remove_action="purge"
+   else
+      remove_action="remove"
+   fi
+
+   printf '%s\n' "$0: INFO: '${remove_action}'ing package '${package_to_replace}' and installing 'dummy-${package_to_replace}'..."
+   printf '%s\n' "$0: EXECUTING: apt-get ${yes_option} ${remove_action} -- ${package_to_replace} ${deb_file_copy}"
+   if apt-get ${yes_option} "${remove_action}" -- "${package_to_replace}" "${deb_file_copy}" ; then
       printf '%s\n' "$0: INFO: Dummy package installed."
    else
-      printf '%s\n' "$0: ERROR: 'apt-get install' command failed!" >&2
+      printf '%s\n' "$0: ERROR: 'apt-get' command failed!" >&2
       exit 1
    fi
 
-   printf '%s\n' "$0: INFO: Removing package: '${package_to_replace}'"
-   if [ "${remove_option}" = '--remove' ]; then
-      printf '%s\n' "$0: INFO: Not purging old package configuration files... (Because not using '--purge'.)"
-      printf '%s\n' "$0: INFO: Executing: apt-get ${yes_option} remove -- ${package_to_replace}"
-      if apt-get ${yes_option} remove -- "${package_to_replace}" ; then
-         printf '%s\n' "$0: INFO: Package removed."
-      else
-         printf '%s\n' "$0: ERROR: 'apt-get remove' command failed!" >&2
-         exit 1
-      fi
-   elif [ "${remove_option}" = '--purge' ]; then
-      printf '%s\n' "$0: INFO: Purging old package configuration files..."
-      printf '%s\n' "$0: INFO: Executing: apt-get ${yes_option} purge -- ${package_to_replace}"
-      if apt-get ${yes_option} purge -- "${package_to_replace}" ; then
-         printf '%s\n' "$0: INFO: Package purged."
-      else
-         printf '%s\n' "$0: ERROR: 'apt-get purge' command failed!" >&2
-         exit 1
-      fi
-   fi
-
-   cleanup
-   trap '' EXIT
    printf '%s\n' "$0: INFO: Done."
    exit 0
 }
