fix

diff --git a/usr/bin/localectl-static b/usr/bin/localectl-static
--- a/usr/bin/localectl-static
+++ b/usr/bin/localectl-static
@@ -28,7 +28,14 @@ while [ -n "${1:-}" ]; do
       ;;
    esac
 done
+
 args=( "$@" )
+subcommand="${args[0]:-}"
+
+if [ -z "$subcommand" ]; then
+  printf '%s\n' "$0: ERROR: Missing command (expected: list-x11-keymap-layouts|list-x11-keymap-variants|list-x11-keymap-options)"
+  exit 1
+fi
 
 helper_scripts_share_dir='/usr/share/helper-scripts'
 layouts_static_file="${helper_scripts_share_dir}/localectl-list-x11-keymap-layouts-static.txt"
@@ -43,10 +50,10 @@ if [ "${args[0]}" = "list-x11-keymap-layouts" ]; then
   fi
 elif [ "${args[0]}" = "list-x11-keymap-variants" ]; then
   if [ -z "${args[1]:-}" ]; then
-    printf '%s\n' "ERROR: Display of all keymap variants for all layouts not yet implemented!"
+    printf '%s\n' "ERROR: Missing layout argument!"
     exit 1
   fi
-  if ! [ -f "${variants_static_dir}" ]; then
+  if ! [ -r "${variants_static_dir}" ]; then
     printf '%s\n' "ERROR: Unrecognized keymap '${args[1]}'!"
     exit 1
   fi
