refactoring

diff --git a/usr/bin/luks-path-check b/usr/bin/luks-path-check
--- a/usr/bin/luks-path-check
+++ b/usr/bin/luks-path-check
@@ -17,59 +17,59 @@ exit_function() {
 }
 
 bail_if_not_on_luks() {
-   local swap_mount_device swap_mount_real_device swap_mount_slave_dev \
-      blkid_swap_mount_fs
+   local file_mount_device file_mount_real_device file_mount_slave_dev \
+      blkid_file_mount_fs
 
-   swap_mount_device="$(findmnt --noheadings --output=SOURCE --target "$dirname_file")" || true
+   file_mount_device="$(findmnt --noheadings --output=SOURCE --target "$dirname_file")" || true
    ## example:
-   #swap_mount_device="/dev/mapper/dmroot"
-   if [ -z "$swap_mount_device" ]; then
-      printf '%s\n' "ERROR: No mountpoint source device found for file '$SWAPFILE'!" >&2
+   #file_mount_device="/dev/mapper/dmroot"
+   if [ -z "$file_mount_device" ]; then
+      printf '%s\n' "ERROR: No mountpoint source device found for file '$FILE'!" >&2
       exit 1
    fi
-   if ! [[ "$swap_mount_device" = '/dev/mapper/'* ]]; then
-      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' is not a device-mapper device, exiting, ok."
+   if ! [[ "$file_mount_device" = '/dev/mapper/'* ]]; then
+      printf '%s\n' "INFO: File mountpoint source device '$file_mount_device' is not a device-mapper device, exiting, ok."
       exit_function 0
    fi
 
-   swap_mount_real_device="$(readlink -f -- "$swap_mount_device")" || true
-   if [ -z "$swap_mount_real_device" ]; then
-      printf '%s\n' "ERROR: Cannot find true source device for file mountpoint device '$swap_mount_device'!" >&2
+   file_mount_real_device="$(readlink -f -- "$file_mount_device")" || true
+   if [ -z "$file_mount_real_device" ]; then
+      printf '%s\n' "ERROR: Cannot find true source device for file mountpoint device '$file_mount_device'!" >&2
       exit_function 1
    fi
-   #swap_mount_real_device="$(basename -- "$swap_mount_real_device")"
-   swap_mount_real_device="${swap_mount_real_device##*/}"
+   #file_mount_real_device="$(basename -- "$file_mount_real_device")"
+   file_mount_real_device="${file_mount_real_device##*/}"
 
-   if ! [[ "$swap_mount_real_device" = dm-* ]]; then
-      printf '%s\n' "ERROR: Swapfile mountpoint source device '/dev/$swap_mount_real_device' is not a device-mapper device, exiting, ok." >&2
+   if ! [[ "$file_mount_real_device" = dm-* ]]; then
+      printf '%s\n' "ERROR: File mountpoint source device '/dev/$file_mount_real_device' is not a device-mapper device, exiting, ok." >&2
       exit_function 1
    fi
 
-   swap_mount_slave_dev="$(find "/sys/block/$swap_mount_real_device/slaves" -mindepth 1 2>/dev/null)" || true
+   file_mount_slave_dev="$(find "/sys/block/$file_mount_real_device/slaves" -mindepth 1 2>/dev/null)" || true
    ## example
-   ## swap_mount_slave_dev=''
-   if [ "$swap_mount_slave_dev" = "" ] || [ "$(wc -l <<< "$swap_mount_slave_dev")" != '1' ]; then
-      printf '%s\n' "INFO: Swapfile mountpoint source device '$swap_mount_device' has an incorrect number of slave devices to be a LUKS device, exiting, ok."
+   ## file_mount_slave_dev=''
+   if [ "$file_mount_slave_dev" = "" ] || [ "$(wc -l <<< "$file_mount_slave_dev")" != '1' ]; then
+      printf '%s\n' "INFO: File mountpoint source device '$file_mount_device' has an incorrect number of slave devices to be a LUKS device, exiting, ok."
       printf '%s\n' "Slave devices:"
-      printf '%s\n' "'$swap_mount_slave_dev'"
+      printf '%s\n' "'$file_mount_slave_dev'"
       exit_function 0
    fi
 
-   #swap_mount_slave_dev="$(basename -- "$swap_mount_slave_dev")"
-   swap_mount_slave_dev="${swap_mount_slave_dev##*/}"
+   #file_mount_slave_dev="$(basename -- "$file_mount_slave_dev")"
+   file_mount_slave_dev="${file_mount_slave_dev##*/}"
 
-   if ! [ -b "/dev/$swap_mount_slave_dev" ]; then
-      printf '%s\n' "ERROR: Swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev' does not exist!" >&2
+   if ! [ -b "/dev/$file_mount_slave_dev" ]; then
+      printf '%s\n' "ERROR: File mountpoint underlying device '/dev/$file_mount_slave_dev' does not exist!" >&2
       exit_function 1
    fi
 
-   blkid_swap_mount_fs="$(blkid -s TYPE -o value "/dev/$swap_mount_slave_dev")" || true
-   if [ -z "$blkid_swap_mount_fs" ]; then
-      printf '%s\n' "INFO: 'blkid' did not return the filesystem on file mountpoint underlying device '/dev/$swap_mount_slave_dev', exiting, ok."
+   blkid_file_mount_fs="$(blkid -s TYPE -o value "/dev/$file_mount_slave_dev")" || true
+   if [ -z "$blkid_file_mount_fs" ]; then
+      printf '%s\n' "INFO: 'blkid' did not return the filesystem on file mountpoint underlying device '/dev/$file_mount_slave_dev', exiting, ok."
       exit_function 0
    fi
-   if [ "$blkid_swap_mount_fs" != 'crypto_LUKS' ]; then
-      printf '%s\n' "INFO: Swapfile mountpoint underlying device '/dev/$swap_mount_slave_dev' is not a LUKS device, exiting, ok."
+   if [ "$blkid_file_mount_fs" != 'crypto_LUKS' ]; then
+      printf '%s\n' "INFO: File mountpoint underlying device '/dev/$file_mount_slave_dev' is not a LUKS device, exiting, ok."
       exit_function 0
    fi
 }
