output

diff --git a/usr/bin/luks-path-check b/usr/bin/luks-path-check
--- a/usr/bin/luks-path-check
+++ b/usr/bin/luks-path-check
@@ -32,20 +32,20 @@ bail_if_not_on_luks() {
       exit 1
    fi
    if ! [[ "$file_mount_device" = '/dev/mapper/'* ]]; then
-      printf '%s\n' "INFO: File mountpoint source device '$file_mount_device' is not a device-mapper device, exiting, ok."
+      printf '%s\n' "ERROR: File mountpoint source device '$file_mount_device' is not a device-mapper device." >&2
       exit_function 0
    fi
 
    file_mount_real_device="$(readlink -f -- "$file_mount_device")" || true
    if [ -z "$file_mount_real_device" ]; then
-      printf '%s\n' "ERROR: Cannot find true source device for file mountpoint device '$file_mount_device'!" >&2
+      printf '%s\n' "ERROR: Cannot find true source device for file mountpoint device '$file_mount_device'." >&2
       exit_function 1
    fi
    #file_mount_real_device="$(basename -- "$file_mount_real_device")"
    file_mount_real_device="${file_mount_real_device##*/}"
 
    if ! [[ "$file_mount_real_device" = dm-* ]]; then
-      printf '%s\n' "ERROR: File mountpoint source device '/dev/$file_mount_real_device' is not a device-mapper device, exiting, ok." >&2
+      printf '%s\n' "ERROR: File mountpoint source device '/dev/$file_mount_real_device' is not a device-mapper device." >&2
       exit_function 1
    fi
 
@@ -53,8 +53,8 @@ bail_if_not_on_luks() {
    ## example
    ## file_mount_slave_dev=''
    if [ "$file_mount_slave_dev" = "" ] || [ "$(wc -l <<< "$file_mount_slave_dev")" != '1' ]; then
-      printf '%s\n' "INFO: File mountpoint source device '$file_mount_device' has an incorrect number of slave devices to be a LUKS device, exiting, ok."
-      printf '%s\n' "Slave devices:"
+      printf '%s\n' "ERROR: File mountpoint source device '$file_mount_device' has an incorrect number of slave devices to be a LUKS device." >&2
+      printf '%s\n' "ERROR: Slave devices:" >&2
       printf '%s\n' "'$file_mount_slave_dev'"
       exit_function 0
    fi
@@ -63,17 +63,17 @@ bail_if_not_on_luks() {
    file_mount_slave_dev="${file_mount_slave_dev##*/}"
 
    if ! [ -b "/dev/$file_mount_slave_dev" ]; then
-      printf '%s\n' "ERROR: File mountpoint underlying device '/dev/$file_mount_slave_dev' does not exist!" >&2
+      printf '%s\n' "ERROR: File mountpoint underlying device '/dev/$file_mount_slave_dev' does not exist." >&2
       exit_function 1
    fi
 
    blkid_file_mount_fs="$(blkid -s TYPE -o value "/dev/$file_mount_slave_dev")" || true
    if [ -z "$blkid_file_mount_fs" ]; then
-      printf '%s\n' "INFO: 'blkid' did not return the filesystem on file mountpoint underlying device '/dev/$file_mount_slave_dev', exiting, ok."
+      printf '%s\n' "INFO: 'blkid' did not return the filesystem on file mountpoint underlying device '/dev/$file_mount_slave_dev'."
       exit_function 0
    fi
    if [ "$blkid_file_mount_fs" != 'crypto_LUKS' ]; then
-      printf '%s\n' "INFO: File mountpoint underlying device '/dev/$file_mount_slave_dev' is not a LUKS device, exiting, ok."
+      printf '%s\n' "INFO: File mountpoint underlying device '/dev/$file_mount_slave_dev' is not a LUKS device."
       exit_function 0
    fi
 }
