fix

diff --git a/usr/bin/text-safety-scan b/usr/bin/text-safety-scan
--- a/usr/bin/text-safety-scan
+++ b/usr/bin/text-safety-scan
@@ -3,6 +3,8 @@
 ## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
 ## See the file COPYING for copying conditions.
 
+## Exit non-zero after the first failed plugin.
+
 set -o errexit
 set -o nounset
 set -o errtrace
@@ -12,30 +14,23 @@ set -o pipefail
 source /usr/libexec/helper-scripts/log_run_die.sh
 
 run_plugin_command() {
-  local plugin_cmd plugin_args plugin_exit_code
+  local plugin_cmd plugin_args
 
   plugin_cmd="$1"
   shift
   plugin_args=( "$@" )
-  plugin_exit_code='0'
 
   if (( ${#plugin_args[@]} == 0 )); then
     ## captured_stdin inherited from text_safety_scan function.
-    "${plugin_cmd}" < "${captured_stdin_file}" || plugin_exit_code="$?"
+    "${plugin_cmd}" < "${captured_stdin_file}"
   else
-    "${plugin_cmd}" "${plugin_args[@]}" || plugin_exit_code="$?"
-  fi
-
-  ## exit_code inherited from text_safety_scan function.
-  if [ "$plugin_exit_code" -gt "${exit_code-0}" ]; then
-    exit_code="${plugin_exit_code}"
-    return "$exit_code"
+    "${plugin_cmd}" "${plugin_args[@]}"
   fi
 }
 
 cleanup() {
   local _exit_code="${1:-$?}"
-  trap - ERR EXIT INT TERM HUP QUIT
+  trap - EXIT
   ## captured_stdin_file is inherited from text_safety_scan function.
   ## captured_stdin_file is set prior setting up the 'trap'.
   safe-rm -f -- "${captured_stdin_file}"
@@ -43,14 +38,14 @@ cleanup() {
 }
 
 text_safety_scan() {
-  local file_list captured_stdin_file file plugin_list plugin
+  local file_list captured_stdin_file file_name plugin_list plugin
 
   file_list=( "$@" )
   plugin_list=( 'unicode-show' 'modeline-show' )
 
   if (( ${#file_list[@]} == 0 )); then
     if [[ -t 0 ]]; then
-      die 1 'stdin is not open!'
+      die 1 'No input files and stdin is a terminal.'
     fi
     ## Using a temp file rather than capturing to a variable because Bash will
     ## strip trailing newlines from captured text, potentially distorting the
@@ -58,7 +53,7 @@ text_safety_scan() {
     if ! captured_stdin_file="$(mktemp)"; then
       die 1 'Could not create temporary file for capturing stdin!'
     fi
-    trap 'cleanup' ERR EXIT INT TERM HUP QUIT
+    trap 'cleanup' EXIT
 
     cat | sponge -- "${captured_stdin_file}"
 
@@ -68,9 +63,12 @@ text_safety_scan() {
 
     cleanup
   else
-    for file in "${file_list[@]}"; do
+    for file_name in "${file_list[@]}"; do
+      if ! test -r "$file_name"; then
+        die 1 "File '$file_name' does not exist or is not readable!"
+      fi
       for plugin in "${plugin_list[@]}"; do
-        run_plugin_command "${plugin}" "${file}"
+        run_plugin_command "${plugin}" "${file_name}"
       done
     done
   fi
