improve

diff --git a/usr/bin/text-safety-scan b/usr/bin/text-safety-scan
--- a/usr/bin/text-safety-scan
+++ b/usr/bin/text-safety-scan
@@ -13,8 +13,11 @@ set -o pipefail
 # shellcheck source=../libexec/helper-scripts/log_run_die.sh
 source /usr/libexec/helper-scripts/log_run_die.sh
 
+log_level=info
+
 run_plugin_command() {
-  local plugin_cmd plugin_args
+  declare -g plugin_cmd
+  local plugin_args
 
   plugin_cmd="$1"
   shift
@@ -26,6 +29,8 @@ run_plugin_command() {
   else
     "${plugin_cmd}" "${plugin_args[@]}"
   fi
+
+  log info "${plugin_cmd} OK"
 }
 
 cleanup() {
@@ -34,10 +39,26 @@ cleanup() {
   ## captured_stdin_file is inherited from text_safety_scan function.
   ## captured_stdin_file is set prior setting up the 'trap'.
   if [ -n "${captured_stdin_file-}" ]; then
-    safe-rm -f -- "${captured_stdin_file}"
+    safe-rm --force --verbose -- "${captured_stdin_file}"
+  fi
+  if [ "$_exit_code" = "0" ]; then
+    log notice "OK"
+  else
+    log error "FAIL"
   fi
   exit "${_exit_code}"
 }
+
+error_handler() {
+  local _exit_code="${1:-$?}"
+  trap - ERR
+  log error "FAILED: ${plugin_cmd-"${BASH_COMMAND}"}"
+  exit "${_exit_code}"
+}
+
+trap 'cleanup' EXIT
+
+trap "error_handler" ERR
 
 text_safety_scan() {
   local file_list captured_stdin_file file_name plugin_list plugin_item
@@ -55,15 +76,12 @@ text_safety_scan() {
     if ! captured_stdin_file="$(mktemp)"; then
       die 1 'Could not create temporary file for capturing stdin!'
     fi
-    trap 'cleanup' EXIT
 
     cat | sponge -- "${captured_stdin_file}"
 
     for plugin_item in "${plugin_list[@]}"; do
       run_plugin_command "${plugin_item}"
     done
-
-    cleanup
   else
     for file_name in "${file_list[@]}"; do
       if ! test -r "$file_name"; then
